### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Titef84/kinozal-template-init-project#1]
1)

В файлах установлены разные отступы.
Т.е. в каком-то файле установлены отступы в 2 пробела, в другом файле отступы составляют 4 пробела.
Допускается отступы или 2, или 4, количество отступов должно быть одинаковым для всех файлов проекта, включая HTML, CSS, JS, TS.
Использование символа табуляции, 1 / 3 / 5 / 7 пробелов в качестве отступов - запрещено.
Определитесь с количеством отступов и настройте их число для каждого файла отдельно, а также исправьте количество пробелов для новых файлов по умолчанию.
Как это сделать - описано в документации используемого вами редактора (вопрос гуглится).
После настройки отступов выполните автоматическое форматирование для всех файлов проекта.

![image](https://user-images.githubusercontent.com/8464662/153874917-af6569c9-c91a-4746-a079-c2ff8ce86706.png)

2)
Разрывов полей при переносах быть не должно.
![image](https://user-images.githubusercontent.com/8464662/153875230-e12c6e8f-d581-4263-9a66-d0e1cad42a1d.png)

**Comment by Titef84** [comment]
Внес изменения по замечаниям

**Comment by Alecto** [comment]
Для сдачи проекта требуются две ссылки:
1 - на страницу github pages.
2 - на страницу репозитория.
Все описание есть в документации, в разделе "Критерии сдачи проекта".


пн, 14 лют. 2022 р. о 17:39 Titef84 ***@***.***> пише:

**Comment by Titef84** [comment]
https://github.com/Titef84/kinozal-template-init-project/
https://titef84.github.io/kinozal-template-init-project/

**Comment by Alecto** [comment]
1 - не исправлено

**Comment by Titef84** [comment]
Извиняюсь,  потерял некоторые файлы
https://github.com/Titef84/kinozal-template-init-project/
https://titef84.github.io/kinozal-template-init-project/
